### ISSUE TITLE
Research SmartDashboard for Drive subsystem

### ISSUE THREAD

**Issue by arjunrao87** [frc4571/FRC2017Robot#10]

**Comment by HeyItsConorRyan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Research and implement SmartDashboard for Drive subsystem](https://trello.com/c/180YcEDG/84-research-and-implement-smartdashboard-for-drive-subsystem)

**Comment by arjunrao87** [comment]
This is just to read and understand what you need to get done. There is a different issue i opened for implementation .
