### ISSUE TITLE
Simple autonomous command for drive subsystem

### ISSUE THREAD

**Issue by arjunrao87** [frc4571/FRC2017Robot#2]
Drive Train + Autonomous Command ( Move past Baseline )

**Comment by HeyItsConorRyan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Simple autonomous command for drive subsystem](https://trello.com/c/uf4FxB6L/51-simple-autonomous-command-for-drive-subsystem)

**Comment by arjunrao87** [comment]
Move the robot continuously for 10 seconds forward and then 5 seconds backward.
