### ISSUE TITLE
Adding wheel encoders to drive subsystem

### ISSUE THREAD

**Issue by arjunrao87** [frc4571/FRC2017Robot#3]
Drive Train + PID loop + Quadrature Wheel Encoders

**Comment by HeyItsConorRyan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adding control loops to drive subsystem](https://trello.com/c/R5cLDl5O/52-adding-control-loops-to-drive-subsystem)

**Comment by arjunrao87** [comment]
https://github.com/FRCTeam4500/2016Robot/blob/master/src/org/usfirst/frc/team4500/robot/subsystems/Drivetrain.java
