### ISSUE TITLE
Read up on PID control loops

### ISSUE THREAD

**Issue by arjunrao87** [frc4571/FRC2017Robot#5]

**Comment by arjunrao87** [comment]
http://wpilib.screenstepslive.com/s/3120/m/7912/l/79828-operating-the-robot-with-feedback-from-sensors-pid-control

**Comment by HeyItsConorRyan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Read up on PID control loops](https://trello.com/c/OJrVS5Ij/54-read-up-on-pid-control-loops)

**Comment by arjunrao87** [comment]
http://wpilib.screenstepslive.com/s/4485/m/13809/l/599736-pidsubsystems-for-built-in-pid-control

**Comment by arjunrao87** [comment]
Added a whole bunch of really good resources here : https://github.com/frc4571/FRC2017Robot/wiki/PID-Control-Loops-Resources

I will try to sort them in order of importance

**Comment by arjunrao87** [comment]
http://www.simbotics.org/resources/programming/pid
