### ISSUE TITLE
Flash and image the RoboRio

### ISSUE THREAD

**Issue by arjunrao87** [frc4571/FRC2017Robot#8]

**Comment by arjunrao87** [comment]
- http://wpilib.screenstepslive.com/s/4485/m/13503/l/599670-installing-the-frc-2017-update-suite-all-languages

- http://wpilib.screenstepslive.com/s/4485/m/13503/l/144984-imaging-your-roborio

**Comment by HeyItsConorRyan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flash and image the roborio](https://trello.com/c/fGL2Yt6M/57-flash-and-image-the-roborio)
